language: node_js
node_js:
- 7.5.0
before_script: npm install
script: npm start
before_install:
- openssl aes-256-cbc -K $encrypted_7c523c238872_key -iv $encrypted_7c523c238872_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host drawer.3dmodel.cc\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- npm prune --production
- tar -jcf all.tar.bz2 *
- scp all.tar.bz2 ubuntu@drawer.3dmodel.cc:~
- ssh ubuntu@drawer.3dmodel.cc 'mkdir -p starter && tar -jxf all.tar.bz2 -C starter
  && rm all.tar.bz2'
